packages:
  - "."

allowBuilds:
  '@firebase/util': true
  core-js: set this to true or false
  esbuild: true
  protobufjs: true

onlyBuiltDependencies:
  - "@firebase/util"
  - esbuild
  - protobufjs
